### ISSUE TITLE
Feature Request: Implement clipboard plugin

### ISSUE THREAD

**Issue by LinqLover** [codefrau/SqueakJS#110]
It would be nice to exchange at least text between a SqueakJS image and the host system. ATM, this appears not to be supported.

**Comment by codefrau** [comment]
It works fine on Chrome. Other browsers don’t work quite as well, that’s bug #74. It would be great if someone could look into that :)

**Comment by codefrau** [comment]
If you are on Chrome and Cmd-C/V (Mac) or Ctrl-C/V (Win/Linux) are not working, please re-open, and give it a better title :)

**Comment by LinqLover** [comment]
I'm quite sure it did not work earlier, but at the moment, it is fine. Will reopen if I succeed to reproduce the issue. :-)
