### ISSUE TITLE
Error on loading squeak.js -- line 29

### ISSUE THREAD

**Issue by nmingotti** [codefrau/SqueakJS#129]
Hi, 

I tried to run in my local server and I get this error in the browser:

Uncaught SyntaxError: import declarations may only appear at top level of a module squeak.js:29

bye
n.

**Comment by nmingotti** [comment]
Solved, put this in the HTML file

    <script type="module" src="SqueakJS/squeak.js"></script>

**Comment by codefrau** [comment]
Ah, yes. Alternatively, you can use the pre-built all-in-one file at https://github.com/codefrau/SqueakJS/tree/main/dist which does not require the module syntax.
