### ISSUE TITLE
Very frequent "primitive 176 not implemented" in debugger running Cuis image

### ISSUE THREAD

**Issue by nmingotti** [codefrau/SqueakJS#130]
Just a reminder. Of course if its not implemented its not implemented ;)

**Comment by codefrau** [comment]
For the numbered primitives we know about, we only print a warning once.

Having a numbered primitive we don't know about is potentially fatal so we log an error,

So thanks for this grabbing your attention :) I didn't know `primitiveMaxIdentityHash` existed, it appears to be unused in Squeak.

Now that we know about it we can turn it into a warning, or even just implement it.

**Comment by codefrau** [comment]
Can you try this with a Cuis image? If it works we can make new release.

**Comment by nmingotti** [comment]
Done, far better now ! there are only a reasonable amount of messages in the JS developer console. Thanks.
