### ISSUE TITLE
Custom pointer shapes not shown in Mac Safari

### ISSUE THREAD

**Issue by codefrau** [codefrau/SqueakJS#133]
E.g. hovering the mouse pointer over a window edge should show the resize arrows.

Still works in Chrome, does not work in Safari anymore. I see the hotspot jump, but the cursor shape does not change.

**Comment by ccrraaiigg** [comment]
Hm, strange, it still works for Caffeine (e.g., https://caffeine.js.org/spa ). Then again, I'm behind and haven't even done the ESM changes yet.

**Comment by codefrau** [comment]
It works in Safari Technology Preview Release 178 (Safari 17.0, WebKit 18617.1.6) ... let's hope it works in next Safari then.

**Comment by codefrau** [comment]
Appears to have resolved itself
