### ISSUE TITLE
Squeak 6.0 image format unknown

### ISSUE THREAD

**Issue by codefrau** [codefrau/SqueakJS#137]
E.g. https://squeak.js.org/run/#zip=https://files.squeak.org/6.0/Squeak6.0-22101-32bit/Squeak6.0-22101-32bit.zip
results in

    Error: bad image version

Likely we just need to add the new image format magic numbers. The VM does support Sista V1 bytecodes.

**Comment by fniephaus** [comment]
Yes, maybe you just need to accept-list the version number of the new image format. Here's how we did this in TruffleSqueak: https://github.com/hpi-swa/trufflesqueak/commit/10388ecf75e394241073bf9caa730a8aa6668769#diff-3e25f263607346c79846a7cf80f602bc8d6d42f8f43cd5c3fdff9d59db31a756R20
