### ISSUE TITLE
I succeeded in running squeakJS in the web browser. But, ...

### ISSUE THREAD

**Issue by bemoregt** [codefrau/SqueakJS#143]
Hi, @zot @jsparkes @timfel @krono @luque 

As instructed, 
I succeeded in running squeakJS in the web browser. 
However, even if I run squeak.image to start the wiki server, 
the ComSwiiki page does not appear on my intranet browser. 

Why is this?

My Trial: OSX monterey, m1 macmini, Chrome Browser 109.0.x

**Comment by codefrau** [comment]
JavaScript in a web browser cannot be used to provide a web server. That's why SqueakJS cannot be used to run ComSwiki.

I'm wondering what instructions you were trying to follow?
