### ISSUE TITLE
I cant open my projects in scratch.js.org

### ISSUE THREAD

**Issue by GodOfMachinesALT** [codefrau/SqueakJS#144]
Hi,
in scratch.js.org when i open a saved project, it says that it could not read project. Can you add an option to upload a project from your computer so i can open my work?

**Comment by GodOfMachinesALT** [comment]
Btw, im on an IOS ipad

**Comment by codefrau** [comment]
I'm assuming you mean [squeak.js.org/scratch](https://squeak.js.org/scratch/#fullscreen) not [scratch.js.org](https://scratch.js.org) right?

Note that this is the Squeak version of Scratch (a.k.a. Scratch 1.4) which cannot load files from newer Scratch versions (see https://en.scratch-wiki.info/wiki/Scratch_Versions) (so only `.sb` not `sb2` or `.sb3`).

I agree that adding a file upload button would be useful, especially for mobile devices.

However, on iPad you can drag a Scratch project directly from the [Files app](https://apps.apple.com/us/app/files/id1232058109?platform=ipad) into Scratch (I opened the Files app as a  [Slide Over window](https://support.apple.com/guide/ipad/switch-an-app-window-to-slide-over-ipadfe7c65e9/ipados), but [Split View](https://support.apple.com/guide/ipad/open-two-items-in-split-view-ipad08c9970c/ipados) would work as well):

![IMG_0810](https://user-images.githubusercontent.com/733388/231255172-faacc3ca-162f-4a5d-a26c-abb52e54098f.PNG)

![IMG_0808](https://user-images.githubusercontent.com/733388/231255142-ab169607-5778-4d14-8c5c-1f67c0208a75.PNG)

![IMG_0809](https://user-images.githubusercontent.com/733388/231255188-0bb747d7-158c-4175-8a1b-18e11d769593.PNG)

You may notice the icons of `.sb` files – that is @SoftUmeYa's [Pyonkee](https://www.softumeya.com/pyonkee/en/) app which might be a better way to use Scratch on an iPad than SqueakJS.

**Comment by codefrau** [comment]
Cf issue #145 for adding a file import button

**Comment by GodOfMachinesALT** [comment]
Thanks :)
ill try it out

**Comment by GodOfMachinesALT** [comment]
it says it cant read the file. should i make the file a zip? or do i need to sign into icloud on my ios ipad

**Comment by GodOfMachinesALT** [comment]
Wait, now it says that the file is a bad header.
Btw i cant get pyonkee because im on a school ipad

**Comment by GodOfMachinesALT** [comment]
![IMG_3417](https://user-images.githubusercontent.com/130477851/231482944-6abf5a61-ea97-4a89-b2c8-1ad4bd016f2f.png)
![IMG_3416](https://user-images.githubusercontent.com/130477851/231482964-255c3795-417d-46b6-9164-796d31e3a264.png)

**Comment by GodOfMachinesALT** [comment]
now i forgot how i saved them in a way i could upload

**Comment by GodOfMachinesALT** [comment]
ill send link, i also gave up on sprite uploads bc it is limited and can't upload unless i duplicate the glitched sprite

**Comment by GodOfMachinesALT** [comment]
https://squeak.js.org/run/ this is where i got the files

**Comment by GodOfMachinesALT** [comment]
i saved the projects to the squeak folder, then download the projects from there.

**Comment by GodOfMachinesALT** [comment]
I cant use appstore to get pyonkee bc im on a school ipad

**Comment by GodOfMachinesALT** [comment]
i have found a way to save - if i upload a sprite frim the scratch library, i can edit the code and costumes and then export them. Then it lets me upload them without downloading any files :D
![IMG_3433](https://user-images.githubusercontent.com/130477851/231555057-adcb003c-8455-4fd5-a9f0-5d24cbd09432.png)
(list sorting i made in scratch 1.4) 😀

**Comment by GodOfMachinesALT** [comment]
I guess it works now! :D
