### ISSUE TITLE
Fix writing Scratch projects

### ISSUE THREAD

**Issue by BwenedianJr** [codefrau/SqueakJS#146]
Hi, scratch 1,4 isn’t reading the project files.
I think this has to do with the fact scratch 1.4 was written in a different version of squeak, so it glitches. Also, can you make it so on mobile devices the cursor is hidden? I find the cursor distracting and it makes it hard to click.

**Comment by codefrau** [comment]
> Hi, scratch 1,4 isn’t reading the project files.

Which project files specifically? "json" as per your title is not a Scratch project. 

> I think this has to do with the fact scratch 1.4 was written in a different version of squeak, so it glitches. 

What makes you think this is a different version of Squeak? This is literally running the official Scratch 1.4 image. 

> Also, can you make it so on mobile devices the cursor is hidden? I find the cursor distracting and it makes it hard to click.

Someone could make that happen, certainly. It might be better to separate feature requests from bug reports though. And then find a volunteer to do it.

**Comment by BwenedianJr** [comment]
It says the file might be damaged
Even if I download the file from squeak.jr.org/run it gets corrupted

**Comment by BwenedianJr** [comment]
![IMG_3590](https://github.com/codefrau/SqueakJS/assets/133587602/8345c7be-ceed-40e7-90f3-b4a386dab404)
![IMG_3591](https://github.com/codefrau/SqueakJS/assets/133587602/6187c0ad-9b6a-44a3-977d-feb9fb1887ec)
![IMG_3592](https://github.com/codefrau/SqueakJS/assets/133587602/9b3db542-f7c7-457c-8085-93cf59eaadab)
![IMG_3593](https://github.com/codefrau/SqueakJS/assets/133587602/1c181892-4c02-4d5b-a3d0-74eebcd08c75)
![IMG_3594](https://github.com/codefrau/SqueakJS/assets/133587602/ad8c7c70-84b9-4657-8800-61d02d99ca84)

**Comment by codefrau** [comment]
Hmm, not sure what's wrong. It can load the example projects fine (when you click the Examples folder button) but it cannot load a project I saved ... it is not specific to iPad but happens on desktop too.

Might be a similar issue as in #144 (you could try Pyonkee as suggested there)

I personally do not have time to investigate this any time soon, unfortunately. If you are a Squeak programmer, or you know one, shift-click the loop in the R of the SCRATCH logo to access the Squeak tools and start debugging.

**Comment by BwenedianJr** [comment]
Could you add this Pyonkee image file I found to squeak? https://github.com/SoftUmeYa/Pyonkee/raw/master/Scratch.image

**Comment by codefrau** [comment]
You can run it directly by executing it via this URL 
https://squeak.js.org/run/#image=https://github.com/SoftUmeYa/Pyonkee/raw/master/Scratch.image

It starts to load, but I'd be surprised if it worked well because it likely depends on the Pyonkee environment.

What are you trying to do?

**Comment by BwenedianJr** [comment]
Can you add this to one of the featured images?
https://squeak.js.org/run/#image=https://github.com/NoMod-Programming/Whiskers/raw/master/Build/Whiskers.image
The link doesn’t let me add to Home Screen like scratch 1.4.

**Comment by BwenedianJr** [comment]
I found the saving issue! All you need to do is delete the sounds and it saves!

**Comment by BwenedianJr** [comment]
By the way, that’s my main account. I forgot I made a issue here!

**Comment by codefrau** [comment]
I fixed a file writing bug in release 1.1.0 that might fix the sound writing issue.

**Comment by codefrau** [comment]
Yep, confirmed this works now.

**Comment by BwenedianJr** [comment]
😁 IT WORKS THANK YOU SO MUCH
