### ISSUE TITLE
Links dont work anymore

### ISSUE THREAD

**Issue by FinalyCode** [codefrau/SqueakJS#152]
Autorun links like https://squeak.js.org/run/#image=https://github.com/NoMod-Programming/Whiskers/raw/master/Build/Whiskers.image don’t work anymore for some reason

**Comment by FinalyCode** [comment]
It says “failed to download https://github.com/NoMod-Programming/Whiskers/raw/master/Build/Whiskers.image“
By the way, I am Bwenedian so the error open json code was my issue post. By the way can you put a warning on the launcher page to say that sounds in scratch must’ve deleted or it won’t save?

**Comment by FinalyCode** [comment]
https://squeak.js.org/run/#image=https://github.com/NoMod-Programming/Whiskers-2.8/raw/master/Whiskers.image This is a full link

**Comment by codefrau** [comment]
Fixed
