### ISSUE TITLE
Old 0.x Scratch don't detect key presses

### ISSUE THREAD

**Issue by husqwc** [codefrau/SqueakJS#153]
Old 0.x Scratch versions (such as [14Mar05](https://github.com/medlans/2.0-Archives/blob/main/ScratchXXXYYZZ%20IMAGE%20files/Scratch14Mar05.zip)) don't detect key presses. Tested on the latest version of both Mac and Windows with Chrome, and the bug occurs on both.

**Comment by codefrau** [comment]
This image is slightly broken – it uses both the "new" event primitives and the old polling primitives.

I just added a work-around for that that hopefully should not affect other images.

Thank you for reporting!
