### ISSUE TITLE
iOS: keyboard breaks when sliding on space bar

### ISSUE THREAD

**Issue by codefrau** [codefrau/SqueakJS#166]
Sliding in space bar should move the cursor. Or at least not break input. It only works again after hiding and showing the keyboard.

**Comment by LinqLover** [comment]
This would also be useful for Android (at least the Gboard keyboard supports this gesture, too). By the way, tapping on autocorrection in Gboard also does not delete the first word before, this might be related :)

**Comment by codefrau** [comment]
I also made the sliding generate arrow key events. Hacky but works 188ff828678c7fabf6d8bb488de0fbfe2b7c48e3
