### ISSUE TITLE
Accessing MIDI?

### ISSUE THREAD

**Issue by SimonXHolland** [codefrau/SqueakJS#176]
Probably not a bug, probably just me being slow, but a sentence of documentation might be useful here.
Very excited to see from squeak.js.org that MIDI plugins are part of the  March 2024 Release 1.2.0, but a bit unsure how to access MIDI  in SqueakJS. Any words of advice or example invocations highly welcome.
For context, the MIDI plugins stopped working in MacOS when everything went 64 bit after Mojave, though I am fairly sure that at least MIDI out still works on Windows.

**Comment by codefrau** [comment]
Yes, this is not specific to SqueakJS at all but how you play MIDI in Squeak in general. Here is the announcement I posted to squeak-dev in March:

> As of just now, SqueakJS supports actual MIDI 🥳 At least in Chrome:
> 
> https://squeak.js.org/
> 
> You can run an image, drop in a MIDI file, and play it.
> 
> I don't have a hardware synth so I tested MIDI output via GarageBand. The Steinway Grand sounds great playing the Moonlight sonata. Here's a video with sound:
> 
> https://freudenbergs.de/vanessa/squeakjs/SqueakJS-MIDI.mp4
> 
> Should work in pretty much any Squeak version (I tried in 6.2, too).
> 
> I tested MIDI input using the MidiKeys app since I don't have a real keyboard. It's implemented and the data coming into the image looks right, but the MidiSynth class's playback does not sound quite right. 
> 
> Also, it's not entirely clear what epoch/units the midi clock is supposed to be in – possibly because Squeak changed millisecondClockValue to not start at 0 anymore, whereas older images (or at least the MIDI code in it) expects that.
> 
> If anyone wants to hack it, my WebMIDI plugin code is in:
> 
> https://github.com/codefrau/SqueakJS/blob/main/plugins/MIDIPlugin.js
> 
> Have fun 💜

**Comment by SimonXHolland** [comment]
Thanks - that's super helpful. The video makes it easy to check exactly what smalltalk code is being used. If I get a chance later on,  I'll try to look at midi in,  in case its a simple midi thing, like a one-off channel error.

**Comment by SimonXHolland** [comment]
Still not a bug, but an extra hint may be needed for naïve end users to get MIDI to work in SqueakJS

a)	A dropped midi file does indeed play right away with https://squeak.js.org/etoys/ in safari or chrome, but an inspector on the scorePlayer shows that this is running the internal squeak FM synthesizer, not MIDIPlugin.js. Am I missing some kind of binding step?

b)	Similarly, I tried loading a clean 6.0-22148 64 bit release from https://squeak.org/downloads/  together with MIDIPlugin.js into a clean  SqueakJS minilauncher, but all of the MidiPrimTester tests got ‘primitive failed’ results.

c)	Similarly the highly reliable MIDI workhorse method:
SimpleMIDIPort (class) >> examplePlayNoteNamedVelocityOnChannel
Falls over with ‘primitive failed’ when it invokes the following  method with the following argument values:
      portNumber: 	0
      accessSema: 	a Semaphore()
      lastCommandByteOut: 	nil

SimpleMIDIPort>> primMIDIOpenPort: portNum readSemaIndex: readSemaIndex interfaceClockRate: interfaceClockRate
	"Open the given MIDI port. If non-zero, readSemaIndex specifies the index in the external objects array of a           semaphore to be signalled when incoming MIDI data is available. Not all platforms support signalling the read            semaphore. InterfaceClockRate specifies the clock rate of the external MIDI interface adaptor on Macintosh            computers; it is ignored on other platforms."

	<primitive: 'primitiveMIDIOpenPort' module: 'MIDIPlugin'>
	self primitiveFailed.

Even though this primitive method looks perfectly configured to work with MIDIPlugin.js.
What am I doing wrong?

**Comment by codefrau** [comment]
Do you get a different result with a regular Squeak VM? Like, defaulting to Squeak's own FM synthesis is expected, that's how the Etoys image does it, has nothing to do with SqueakJS. As I show in the video, you need to explicitly choose the "Play via MIDI" menu item, which will show the available MIDI devices if there are any.

For that, of course you need be able to play MIDI in your browser in the first place. Meaning it needs to be a browser supporting MIDI (i.e., not Safari) and you need to have a MIDI device configured. So I'd check some WebMIDI test site first to make sure your system is set up correctly. Once that works you can try in SqueakJS.

**Comment by SimonXHolland** [comment]
My bad for not watching the whole video - thanks! - I'll do some more experiments

**Comment by SimonXHolland** [comment]
Oh my giddy aunt - SqueakJS is running all of my somewhat complicated code flawlessly now! SqueakJS has progressed lightyears  since just two years ago - it's an astounding achievement. (For the record, the key reason for my confusion about Squeak JS's midi facility, apart from not watching more than few seconds of video,  was total ignorance of Chrome and WebMIDI - which Safari of course does not support. Thanks for your patience, Vanessa!

**Comment by codefrau** [comment]
Glad you figured it out 💜
