### ISSUE TITLE
Performance Enhancement: use "requestAnimationFrame" instead of "setTimeout"

### ISSUE THREAD

**Issue by alxbradley** [codefrau/SqueakJS#180]
`setTimeout` depends on the browser's internal event queue and has terrible performance with respect to animations. If other events get added to the queue then your timeout will have to wait until the other events are handled first.

`requestAnimationFrame` on the other hand is a lower level hook into the browser render engine and will run your code before the next frame is painted and does NOT depend on the event queue.

Read more about it here:
https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame

@codefrau

**Comment by codefrau** [comment]
Sure. When I wrote that code in 2013, `rAF` was brand new so I couldn't rely on it.

Send me a PR (but it needs to respect the sleep `ms` for power efficiency).

**Comment by alxbradley** [comment]
I replaced setTimeout with requestAnimationFrame and...performance degraded terribly! `setTimeout(..., 0)` runs way more frequently than requestAnimationFrame. 

It was a fun experiment though...

**Comment by codefrau** [comment]
That is surprising. Thank you for experimenting!
