### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '-1')

### ISSUE THREAD

**Issue by husqwc** [codefrau/SqueakJS#181]
Scratch pre-release version [10Dec05](https://github.com/medlans/2.0-Archives/blob/main/Scratch%200.X-1.X/.ZIP/2005/Scratch10Dec05.zip) spams "TypeError: Cannot read properties of undefined (reading '-1')" when trying to open it. This is the only version I know that does this as far as I'm aware.

**Comment by codefrau** [comment]
I deployed this as version 1.2.3 now – should work
