### ISSUE TITLE
No keyboard on touch devices

### ISSUE THREAD

**Issue by codefrau** [codefrau/SqueakJS#4]
Maybe we need another hack than content-editable? It works fine on desktop Chrome though.

**Comment by bertfreudenberg** [comment]
I added a button, but it still uses `content-editable` and only tested on iOS: 2c28141c5d9044d4727e93fcdd5de296aad89732
We need some proper magic. E.g. it works very badly with predictive text input, when multiple characters are replaced ... Also copy/paste is still an issue #74

**Comment by LinqLover** [comment]
On Chrome for Android, keyboard inputs are not recognized at all, even though I can open up the keyboard thanks to the keyboard button. Sounds as if a hidden text field might be a good solution.

Just for interest, can you use such a dummy field for better recording of events or would you actually have to fill it with some dummy text to get notified when the text changes? And how would you deal with that text field's focus to avoid the keyboard being shown permanently? I don't think the ImmPlugin is supported by all older images, probably not even by non-Morphic projects such as MVC or SqueakShell.

**Comment by codefrau** [comment]
The plugin would use `.focus()` / `.blur()` to manage the focus of the hidden field. The browser will respond by showing/hiding the on-screen keyboard.

As for having a dummy character in the field - I'm not sure. Guess we need to test what events browsers actually deliver.

To support MVC etc we do need the keyboard button I think, because MVC is simply polling the keyboard queue. There might be a hack to walk up the stack context chain to see what kind of Controller is currently doing the polling, but I'm not confident that would even work, let alone be reliable.

**Comment by ErikOnBike** [comment]
A character or two might be needed in the hidden input field to allow a backspace or delete to be signalled as input event (or something similar, don't fully remember and writing this away from the computer). As keyboard event I think they always will be signalled. But not sure if that works on Android. Be careful this event mixing of input va key events is or can be quite a challenge. For IME there can be multiple key and/or input events leading up to a single character being inserted. That is, events can be composing. Copy/paste might need special handling as well. I'm also busy with this kind of stuff at the moment. Will try to give an update if I discovered some useful solution.

**Comment by LinqLover** [comment]
It will be even harder when it comes to non-stroke events (keyDown, keyUp). Probably they could only be simulated if the dummy field receives a stroke. And what's about arrow keys and so on? At least under Android, some keyboards offer arrow keys, so it would also be necessary to track the caret focus of the dummy field. Whew!

**Comment by tonyg** [comment]
Regarding just plain text input on mobile devices, no control- or command-keys, please see https://github.com/codefrau/SqueakJS/pull/135, which could be a basis for discussion. It's pretty janky still but might be an approach polishable into something usable.

**Comment by codefrau** [comment]
Fixed by 4ccac8c9cb566fc5f675aa69f5b02ae96cb63b17
