### ISSUE TITLE
primitiveHashMultiply (159) missing 

### ISSUE THREAD

**Issue by pavel-krivanek** [codefrau/SqueakJS#98]
The primitive primitiveHashMultiply from the set of new primitives is missing. It should at least fail. I use this workaround:
```javascript
            case 159: if (this.oldPrims) return this.primitiveFileRename(argCount);
                else return this.primitiveHashMultiply(argCount);
``` 
where this funciton is defined behind primitiveNotEqualLargeIntegers as:
```javascript
    primitiveHashMultiply: function(numArgs) {
        false;
    },
```

**Comment by bertfreudenberg** [comment]
Failing the primitive should be the default behavior. Isn't that working?

Or is it just that we repeatedly log the missing numbered primitive as an error?
